# /scrapy_models/page.py
import scrapy


class PageItem(scrapy.Item):
    page_id = scrapy.Field()
    audit_id = scrapy.Field()
    url = scrapy.Field()
    load_time = scrapy.Field()
    content_type = scrapy.Field()
    title = scrapy.Field()
    crawl_depth = scrapy.Field()
    h1 = scrapy.Field()
    h2 = scrapy.Field()
    h1_count = scrapy.Field()
    h2_count = scrapy.Field()
    page_link_count = scrapy.Field()
    image_link_count = scrapy.Field()
    internal_link_count = scrapy.Field()
    external_link_count = scrapy.Field()
    images_without_alt_count = scrapy.Field()
    status_code = scrapy.Field()
    title_length = scrapy.Field()
    meta_description_length = scrapy.Field()
    has_meta_keywords = scrapy.Field()
    is_mobile_friendly = scrapy.Field()
    has_structured_data = scrapy.Field()
    is_https = scrapy.Field()
    duplicate_content_flag = scrapy.Field()
    broken_link_count = scrapy.Field()
    meta_description = scrapy.Field()
    title_count = scrapy.Field()
